name: "Setup"
description: "Setup Node, PNPM, and install dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #6.3.0
      with:
        node-version: "lts/*"
        registry-url: https://npm.pkg.github.com
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    - run: npm ci
      shell: bash
