name: "Setup"
description: "Setup Node, PNPM, and install dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://npm.pkg.github.com
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    - run: npm ci
      shell: bash
