name: Lint
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Check working copy
        run: git diff --exit-code
